java:
- "1.7"
language: java
script: mvn clean package

before_install:
  - gem install package_cloud
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - mvn clean package cobertura:cobertura coveralls:cobertura
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r  target/site/cobertura/coverage.xml

# script:
#     - package_cloud push boycook/snapshots/org/cccs/ target/movie-service.jar

deploy:
  provider: elasticbeanstalk
  access_key_id: ...
  secret_access_key:
    secure: ...
  region: "eu-west-2"
  app: "movie-service"
  env: "movie-service-environment"
  bucket_name: "webapp-bucket"