java:
- "1.8"
language: java

cache:
  bundler: true
  directories:
    - .autoconf
    - $HOME/.m2

before_install:
  - sudo apt-get install jq
  - chmod +x scripts/JMeterInstaller.py
  - python scripts/JMeterInstaller.py
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

env: JMETER_PATH=./

jobs:
  include:
    - stage: test
      script: mvn test cobertura:cobertura coveralls:cobertura && java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/cobertura/coverage.xml
#    - stage: publish artifact
#      script: mvn -s .travis.settings.xml deploy
#      skip_cleanup: true
#    - stage: deploy to test
#      script: mvn package
#      deploy:
#        provider: elasticbeanstalk
#        skip_cleanup: true
#        zip_file: target/movie-service.jar
#        access_key_id: $AWS_ACCESS_KEY_ID
#        secret_access_key: $AWS_SECRET_ACCESS_KEY
#        bucket_name: $AWS_BUCKET_NAME
#        region: "eu-west-2"
#        app: "movie-service"
#        env: "movie-service-test"
#    - stage: performance test
#      script:
#        - rm -rf results && mkdir results
#        - apache-jmeter-3.0/bin/jmeter.sh -j results/jmeter.log -p scripts/jmeter.properties -t scripts/load_test.jmx -n -l results/load_test.jtl
#        - scripts/generate_files_from_jtl.sh load_test
