java:
- "1.8"
language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

jobs:
  include:
    - stage: build
      script: mvn clean package
      skip_cleanup: true
    - stage: test
      script: mvn clean test cobertura:cobertura coveralls:cobertura && java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/cobertura/coverage.xml
    - stage: publish artifact
      script: mvn -s .travis.settings.xml clean deploy
      skip_cleanup: true
    - stage: deploy to cloud
      script: mvn clean package
      deploy:
        provider: elasticbeanstalk
        skip_cleanup: true
        zip_file: target/movie-service.jar
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket_name: $AWS_BUCKET_NAME
        region: "eu-west-2"
        app: "movie-service"
        env: "movie-service-test"
